# Generated by Django 6.0.1 on 2026-01-30 02:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='python', max_length=20)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('file_path', models.CharField(blank=True, default='', help_text='Derived path for Git export, e.g. code/slug.py', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tool_type', models.CharField(choices=[('web_search', 'Web Search'), ('browser', 'Browser'), ('api', 'API'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('input_schema', models.JSONField(blank=True, null=True)),
                ('default_config', models.JSONField(default=dict)),
                ('credential_type', models.CharField(blank=True, default='', help_text='What credential type is needed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CodeBlockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_data', models.JSONField()),
                ('expected_output', models.JSONField(blank=True, null=True)),
                ('expected_error', models.CharField(blank=True, default='', max_length=500)),
                ('code_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='workflows.codeblock')),
            ],
        ),
        migrations.CreateModel(
            name='CodeBlockVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('code', models.TextField()),
                ('code_hash', models.CharField(help_text='SHA256 hash', max_length=64)),
                ('input_schema', models.JSONField(blank=True, null=True)),
                ('output_schema', models.JSONField(blank=True, null=True)),
                ('requirements', models.JSONField(default=list, help_text='pip packages')),
                ('commit_message', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('ui', 'UI'), ('git_pull', 'Git Pull')], default='ui', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('testing', 'Testing'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_versions', to='users.userprofile')),
                ('code_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.codeblock')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='CodeBlockTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('actual_output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows.codeblocktest')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='workflows.codeblockversion')),
            ],
        ),
        migrations.AddField(
            model_name='codeblock',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.codeblockversion'),
        ),
        migrations.AddField(
            model_name='codeblock',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.codeblockversion'),
        ),
        migrations.CreateModel(
            name='ComponentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('categorizer', 'Categorizer'), ('router', 'Router'), ('chat_model', 'Chat Model'), ('react_agent', 'React Agent'), ('plan_and_execute', 'Plan and Execute'), ('tool_node', 'Tool Node'), ('aggregator', 'Aggregator'), ('human_confirmation', 'Human Confirmation'), ('parallel', 'Parallel'), ('workflow', 'Workflow'), ('code', 'Code'), ('loop', 'Loop'), ('wait', 'Wait'), ('merge', 'Merge'), ('filter', 'Filter'), ('transform', 'Transform'), ('sort', 'Sort'), ('limit', 'Limit'), ('http_request', 'HTTP Request'), ('error_handler', 'Error Handler'), ('output_parser', 'Output Parser')], max_length=30)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('extra_config', models.JSONField(default=dict, help_text='temperature, max_tokens, categories, etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('files_changed', models.JSONField(default=list)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('committed_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_commits', to='users.userprofile')),
            ],
            options={
                'ordering': ['-committed_at'],
            },
        ),
        migrations.AddField(
            model_name='codeblockversion',
            name='git_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_versions', to='workflows.gitcommit'),
        ),
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=20)),
                ('remote_url', models.URLField(max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('local_path', models.CharField(max_length=500)),
                ('last_commit_hash', models.CharField(blank=True, default='', max_length=40)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='credentials.gitcredential')),
            ],
            options={
                'verbose_name_plural': 'git repositories',
            },
        ),
        migrations.AddField(
            model_name='gitcommit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='workflows.gitrepository'),
        ),
        migrations.CreateModel(
            name='GitSyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('both', 'Both')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('commit_message', models.TextField(blank=True, default='')),
                ('commit_hash', models.CharField(blank=True, default='', max_length=40)),
                ('files_changed', models.JSONField(default=list)),
                ('error_log', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='workflows.gitrepository')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_sync_tasks', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ToolCredentialMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('tool_credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_mappings', to='credentials.toolcredential')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_credential_mappings', to='users.userprofile')),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_mappings', to='workflows.tooldefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('is_callable', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('input_schema', models.JSONField(blank=True, null=True)),
                ('output_schema', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('default_llm_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_workflows', to='credentials.llmprovidercredentials')),
                ('default_llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_workflows', to='credentials.llmmodel')),
                ('error_handler_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_handled_by', to='workflows.workflow')),
                ('forked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='workflows.workflow')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workflows', to='users.userprofile')),
                ('repository', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow', to='workflows.gitrepository')),
                ('telegram_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='credentials.telegramcredential')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='codeblock',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_blocks', to='workflows.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node_id', models.CharField(max_length=255)),
                ('target_node_id', models.CharField(blank=True, default='', max_length=255)),
                ('edge_type', models.CharField(choices=[('direct', 'Direct'), ('conditional', 'Conditional')], default='direct', max_length=15)),
                ('condition_mapping', models.JSONField(blank=True, help_text='route -> target node mapping for conditional edges', null=True)),
                ('priority', models.IntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflows.workflow')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('execution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_node_id', models.CharField(blank=True, default='', max_length=255)),
                ('thread_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('interrupted', 'Interrupted'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('trigger_payload', models.JSONField(blank=True, null=True)),
                ('final_output', models.JSONField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_executions', to='workflows.workflowexecution')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='users.userprofile')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingTask',
            fields=[
                ('task_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('node_id', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tasks', to='users.userprofile')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tasks', to='workflows.workflowexecution')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=15)),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflows.workflowexecution')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_overrides', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tools', to='workflows.tooldefinition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='workflows.workflow')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('telegram_message', 'Telegram Message'), ('telegram_chat', 'Telegram Chat'), ('schedule', 'Schedule'), ('webhook', 'Webhook'), ('manual', 'Manual'), ('workflow', 'Workflow'), ('error', 'Error')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='workflows.workflow')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='workflows.workflowtrigger'),
        ),
        migrations.AlterUniqueTogether(
            name='codeblockversion',
            unique_together={('code_block', 'version_number')},
        ),
        migrations.CreateModel(
            name='WorkflowCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='users.userprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='users.userprofile')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='workflows.workflow')),
            ],
            options={
                'unique_together': {('workflow', 'user_profile')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('categorizer', 'Categorizer'), ('router', 'Router'), ('chat_model', 'Chat Model'), ('react_agent', 'React Agent'), ('plan_and_execute', 'Plan and Execute'), ('tool_node', 'Tool Node'), ('aggregator', 'Aggregator'), ('human_confirmation', 'Human Confirmation'), ('parallel', 'Parallel'), ('workflow', 'Workflow'), ('code', 'Code'), ('loop', 'Loop'), ('wait', 'Wait'), ('merge', 'Merge'), ('filter', 'Filter'), ('transform', 'Transform'), ('sort', 'Sort'), ('limit', 'Limit'), ('http_request', 'HTTP Request'), ('error_handler', 'Error Handler'), ('output_parser', 'Output Parser')], max_length=30)),
                ('is_entry_point', models.BooleanField(default=False)),
                ('interrupt_before', models.BooleanField(default=False)),
                ('interrupt_after', models.BooleanField(default=False)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='workflows.codeblock')),
                ('component_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.componentconfig')),
                ('subworkflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_subworkflow_in', to='workflows.workflow')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
            options={
                'unique_together': {('workflow', 'node_id')},
            },
        ),
    ]
