# Generated by Django 6.0.1 on 2026-01-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='default_llm_credential',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='default_llm_model',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='telegram_credential',
        ),
    ]
