# Generated by Django 6.0.1 on 2026-01-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('workflows', '0002_remove_workflow_default_llm_credential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentconfig',
            name='llm_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.llmprovidercredentials'),
        ),
        migrations.AddField(
            model_name='workflowtrigger',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='credentials.basecredentials'),
        ),
    ]
