# Generated by Django 6.0.1 on 2026-01-31 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_simplify_llm_credentials'),
        ('workflows', '0004_component_config_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcomponentconfig',
            name='llm_model',
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='frequency_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='max_retries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='presence_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='response_format',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelcomponentconfig',
            name='top_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelcomponentconfig',
            name='llm_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.basecredentials'),
        ),
    ]
