# Generated by Django 6.0.1 on 2026-01-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_simplify_llm_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcomponentconfig',
            name='system_prompt',
        ),
    ]
