# Generated by Django 6.0.1 on 2026-01-31 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_simplify_llm_credentials'),
        ('workflows', '0006_remove_model_system_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecution',
            name='trigger',
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='trigger_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to='workflows.workflownode'),
        ),
        migrations.AlterField(
            model_name='basecomponentconfig',
            name='component_type',
            field=models.CharField(choices=[('categorizer', 'Categorizer'), ('router', 'Router'), ('ai_model', 'AI Model'), ('simple_agent', 'Simple Agent'), ('planner_agent', 'Planner Agent'), ('tool_node', 'Tool Node'), ('aggregator', 'Aggregator'), ('human_confirmation', 'Human Confirmation'), ('parallel', 'Parallel'), ('workflow', 'Workflow'), ('code', 'Code'), ('loop', 'Loop'), ('wait', 'Wait'), ('merge', 'Merge'), ('filter', 'Filter'), ('transform', 'Transform'), ('sort', 'Sort'), ('limit', 'Limit'), ('http_request', 'HTTP Request'), ('error_handler', 'Error Handler'), ('output_parser', 'Output Parser'), ('trigger_telegram', 'Trigger: Telegram'), ('trigger_webhook', 'Trigger: Webhook'), ('trigger_schedule', 'Trigger: Schedule'), ('trigger_manual', 'Trigger: Manual'), ('trigger_workflow', 'Trigger: Workflow'), ('trigger_error', 'Trigger: Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='component_type',
            field=models.CharField(choices=[('categorizer', 'Categorizer'), ('router', 'Router'), ('ai_model', 'AI Model'), ('simple_agent', 'Simple Agent'), ('planner_agent', 'Planner Agent'), ('tool_node', 'Tool Node'), ('aggregator', 'Aggregator'), ('human_confirmation', 'Human Confirmation'), ('parallel', 'Parallel'), ('workflow', 'Workflow'), ('code', 'Code'), ('loop', 'Loop'), ('wait', 'Wait'), ('merge', 'Merge'), ('filter', 'Filter'), ('transform', 'Transform'), ('sort', 'Sort'), ('limit', 'Limit'), ('http_request', 'HTTP Request'), ('error_handler', 'Error Handler'), ('output_parser', 'Output Parser'), ('trigger_telegram', 'Trigger: Telegram'), ('trigger_webhook', 'Trigger: Webhook'), ('trigger_schedule', 'Trigger: Schedule'), ('trigger_manual', 'Trigger: Manual'), ('trigger_workflow', 'Trigger: Workflow'), ('trigger_error', 'Trigger: Error')], max_length=30),
        ),
        migrations.CreateModel(
            name='TriggerComponentConfig',
            fields=[
                ('basecomponentconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.basecomponentconfig')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('trigger_config', models.JSONField(default=dict)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.basecredentials')),
            ],
            bases=('workflows.basecomponentconfig',),
        ),
        migrations.DeleteModel(
            name='WorkflowTrigger',
        ),
    ]
