# Generated by Django 6.0.1 on 2026-01-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_remove_workflowexecution_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecomponentconfig',
            name='component_type',
            field=models.CharField(choices=[('categorizer', 'Categorizer'), ('router', 'Router'), ('extractor', 'Extractor'), ('ai_model', 'AI Model'), ('simple_agent', 'Simple Agent'), ('planner_agent', 'Planner Agent'), ('tool_node', 'Tool Node'), ('aggregator', 'Aggregator'), ('human_confirmation', 'Human Confirmation'), ('parallel', 'Parallel'), ('workflow', 'Workflow'), ('code', 'Code'), ('loop', 'Loop'), ('wait', 'Wait'), ('merge', 'Merge'), ('filter', 'Filter'), ('transform', 'Transform'), ('sort', 'Sort'), ('limit', 'Limit'), ('http_request', 'HTTP Request'), ('error_handler', 'Error Handler'), ('output_parser', 'Output Parser'), ('trigger_telegram', 'Trigger: Telegram'), ('trigger_webhook', 'Trigger: Webhook'), ('trigger_schedule', 'Trigger: Schedule'), ('trigger_manual', 'Trigger: Manual'), ('trigger_workflow', 'Trigger: Workflow'), ('trigger_error', 'Trigger: Error'), ('trigger_chat', 'Trigger: Chat')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='component_type',
            field=models.CharField(choices=[('categorizer', 'Categorizer'), ('router', 'Router'), ('extractor', 'Extractor'), ('ai_model', 'AI Model'), ('simple_agent', 'Simple Agent'), ('planner_agent', 'Planner Agent'), ('tool_node', 'Tool Node'), ('aggregator', 'Aggregator'), ('human_confirmation', 'Human Confirmation'), ('parallel', 'Parallel'), ('workflow', 'Workflow'), ('code', 'Code'), ('loop', 'Loop'), ('wait', 'Wait'), ('merge', 'Merge'), ('filter', 'Filter'), ('transform', 'Transform'), ('sort', 'Sort'), ('limit', 'Limit'), ('http_request', 'HTTP Request'), ('error_handler', 'Error Handler'), ('output_parser', 'Output Parser'), ('trigger_telegram', 'Trigger: Telegram'), ('trigger_webhook', 'Trigger: Webhook'), ('trigger_schedule', 'Trigger: Schedule'), ('trigger_manual', 'Trigger: Manual'), ('trigger_workflow', 'Trigger: Workflow'), ('trigger_error', 'Trigger: Error'), ('trigger_chat', 'Trigger: Chat')], max_length=30),
        ),
    ]
