"""Access layer for binary catalogs.

A *binary* is an external executable that describes itself: `<bin> catalog`
prints the operations it can perform, and `<bin> call <operation>` performs one.
See the bin-contract protocol for the document this module reads.

The catalogs themselves are NOT in this repository. They are generated by
registering each binary (`scripts/register_plugin.py`) into `platform/catalogs/`,
which is gitignored, because a catalog describes one organisation's operations
and this repository is public. Only this reader is committed.

Binary nodes are TWO static component types — `binary_op` and `binary_auth` —
and the binary is node data (`extra_config["binary"]`). Nothing here registers
node types or mapped classes any more: this module answers questions about a
binary's catalog *on demand*, per call, so a catalog registered into an
already-running process is visible on the very next call with no restart.

The catalog file is the pin. It is read from disk, never by shelling out to the
binary: a binary upgrade would otherwise mutate every saved workflow's ports
underneath it, and a port that vanishes does not fail loudly —
`resolve_expressions` turns it into the literal string `{{ node.port }}`
travelling onward as if it were a value. Each file is cached against its mtime,
so repeated calls cost a `stat()` while re-registration (which rewrites the
file) is picked up immediately.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from config import BASE_DIR
from schemas.node_types import DataType, PortDefinition

logger = logging.getLogger(__name__)

CATALOG_DIR = Path(BASE_DIR) / "catalogs"

# Keys the platform itself stores in a binary node's extra_config. A catalog
# parameter with one of these names would be indistinguishable from the
# platform's own key, so colliding parameters are logged and skipped.
RESERVED_CONFIG_KEYS = frozenset({"binary", "domain", "operation", "session", "env"})

# The contract restricts an output's type to exactly the JSON types, which is why
# this mapping is total and needs no fallback for "some type we have not seen".
# `null` alone carries no information about the value's shape, so it maps to ANY.
_TYPE_MAP = {
    "string": DataType.STRING,
    "number": DataType.NUMBER,
    "boolean": DataType.BOOLEAN,
    "object": DataType.OBJECT,
    "array": DataType.ARRAY,
    "null": DataType.ANY,
}

# Per-file cache: absolute path -> (st_mtime_ns, parsed document or None).
# Process-local by design — every process (server, scheduler, each worker) reads
# the file itself, so no cross-process invalidation exists or is needed. A
# rewrite moves the mtime and the next call re-reads; nothing is cached at
# import and nothing survives the file changing.
_CACHE: dict[str, tuple[int, dict[str, Any] | None]] = {}


def _read_catalog(path: Path) -> dict[str, Any] | None:
    """Read one catalog document, or return None with a reason logged.

    A malformed catalog disables its own binary and nothing else. It must not
    take down the server: the file is operator-supplied and may be half-written,
    from an incompatible binary, or absent entirely.
    """
    try:
        doc = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        logger.error("catalog %s is unreadable, skipping: %s", path.name, exc)
        return None

    # A catalog may be handed over either bare or still inside the envelope the
    # binary wrote to stdout. Accept both rather than making the refresh script
    # the only supported path in.
    if isinstance(doc.get("data"), dict) and "operations" in doc.get("data", {}):
        doc = doc["data"]

    if doc.get("protocol") != 1:
        logger.error(
            "catalog %s declares protocol %r, not 1 — refusing the WHOLE catalog "
            "rather than the operations we happen to recognise",
            path.name,
            doc.get("protocol"),
        )
        return None

    missing = [k for k in ("binary", "operations") if k not in doc]
    if missing:
        logger.error("catalog %s is missing %s, skipping", path.name, ", ".join(missing))
        return None
    return doc


def catalog_for(binary: str, catalog_dir: Path | None = None) -> dict[str, Any] | None:
    """The pinned catalog document for one binary, or None.

    None means the binary is unresolvable here: no such file, unreadable,
    refused (wrong protocol / missing keys), or the name is not a plain name.
    The result is cached per file against its mtime, so a catalog written by
    `register_plugin.py` while this process runs is visible on the next call.
    """
    # The name may arrive from node configuration, so it is caller-controlled.
    # A "binary" like `../../etc/anything` must not name a file outside the
    # catalog directory. (The execution path re-checks via services.plugins.)
    if not binary or binary != Path(binary).name or binary in (".", ".."):
        logger.error("refusing catalog lookup for invalid binary name %r", binary)
        return None

    path = (catalog_dir or CATALOG_DIR) / f"{binary}.json"
    key = str(path)
    try:
        mtime_ns = path.stat().st_mtime_ns
    except OSError:
        _CACHE.pop(key, None)
        return None

    cached = _CACHE.get(key)
    if cached is not None and cached[0] == mtime_ns:
        return cached[1]

    doc = _read_catalog(path)
    _CACHE[key] = (mtime_ns, doc)
    return doc


def _operation_entry(op: dict[str, Any]) -> dict[str, Any]:
    """One operation, shaped like the legacy `x-operations` values, plus domain."""
    params = op.get("params") or {}
    properties = dict(params.get("properties") or {})
    required = list(params.get("required") or [])
    colliding = sorted(set(properties) & RESERVED_CONFIG_KEYS)
    if colliding:
        logger.error(
            "operation %s declares parameter(s) %s, which collide with the "
            "platform's own config keys — skipping them",
            op.get("id"),
            ", ".join(colliding),
        )
        for name in colliding:
            properties.pop(name, None)
        required = [r for r in required if r not in colliding]
        params = {**params, "properties": properties, "required": required}

    return {
        "summary": op.get("summary", ""),
        "params": params,
        "session_required": bool((op.get("session") or {}).get("required")),
        "timeout_default_s": op.get("timeout_default_s"),
        "outputs": [out.get("name") for out in op.get("outputs", [])],
        "domain": op.get("domain"),
        # Whether invoking this operation changes state observable outside the
        # binary. Passed through exactly as the catalog declares it — `True`,
        # `False`, or absent (`None`) if the catalog omits it. None is NOT the
        # same as False: the retry guard that reads this must treat "the
        # catalog didn't say" as mutating, never as safe.
        "mutates": op.get("mutates"),
    }


def operations_for(binary: str, catalog_dir: Path | None = None) -> dict[str, dict[str, Any]] | None:
    """The binary's operations keyed by id, or None if the binary is unresolvable.

    Entries carry what the legacy per-type `x-operations` sidecar carried —
    summary, params, session_required, timeout_default_s, output names — plus
    the operation's `domain`.
    """
    doc = catalog_for(binary, catalog_dir)
    if doc is None:
        return None

    operations: dict[str, dict[str, Any]] = {}
    for op in doc.get("operations", []):
        if "id" not in op or "domain" not in op:
            logger.error(
                "catalog for %s has an operation missing id or domain, skipping it", binary
            )
            continue
        operations[op["id"]] = _operation_entry(op)
    return operations


def operation_output_ports(
    binary: str, operation: str, catalog_dir: Path | None = None
) -> list[PortDefinition] | None:
    """The typed output ports of ONE operation, or None if unresolvable.

    None (binary unknown, catalog absent or refused, operation not offered) is
    distinct from `[]` (a resolvable operation that declares no outputs) — the
    caller must not mistake "cannot know" for "knows there are none".
    """
    doc = catalog_for(binary, catalog_dir)
    if doc is None:
        return None
    for op in doc.get("operations", []):
        if op.get("id") == operation:
            return [
                PortDefinition(
                    name=out["name"],
                    data_type=_TYPE_MAP.get(out.get("type"), DataType.ANY),
                    description=out.get("description", ""),
                )
                for out in op.get("outputs", [])
                if out.get("name")
            ]
    return None


def config_schema_for(binary: str, catalog_dir: Path | None = None) -> dict[str, Any] | None:
    """A legacy-shaped config schema covering ALL of the binary's operations.

    The shape is exactly what the per-type specs used to carry — an `operation`
    enum, `session` and `env` properties, `x-binary`, and the `x-operations`
    sidecar (now with per-operation `domain`) — so the frontend's config form
    consumes it unchanged, keyed by the node's binary instead of its type.
    """
    operations = operations_for(binary, catalog_dir)
    if operations is None:
        return None
    return {
        "type": "object",
        "properties": {
            "operation": {
                "type": "string",
                "title": "Operation",
                "enum": sorted(operations),
            },
            "session": {
                "type": "string",
                "title": "Session",
                "description": "Identity handle held by the binary. Required by some operations.",
            },
            "env": {
                "type": "string",
                "title": "Environment",
                "description": "Environment name registered with the binary.",
            },
        },
        "required": ["operation"],
        "x-binary": binary,
        "x-operations": operations,
    }
