"""Node types derived from binary catalogs.

A *binary* is an external executable that describes itself: `<bin> catalog`
prints the operations it can perform, and `<bin> call <operation>` performs one.
See the bin-contract protocol for the document this module reads.

The catalogs themselves are NOT in this repository. They are generated by running
each binary (`scripts/refresh_catalog.py`) into `platform/catalogs/`, which is
gitignored, because a catalog describes one organisation's operations and this
repository is public. Only the loader is committed.

That has a consequence worth stating plainly: **node types derived from a catalog
exist only on machines that have that catalog.** A clone without one registers
nothing, which is correct — it cannot run those binaries either. But a database
holding nodes of a type whose catalog is absent will fail to load them, and that
is the same problem as removing a plugin that workflows still reference. It needs
an answer before this stops being an experiment.

The catalog file is the pin. Node types are read from it at import, never by
shelling out to the binary at startup: a binary upgrade would otherwise mutate
every saved workflow's ports underneath it, and a port that vanishes does not
fail loudly — `resolve_expressions` turns it into the literal string
`{{ node.port }}` travelling onward as if it were a value.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from config import BASE_DIR
from schemas.node_types import DataType, NodeTypeSpec, PortDefinition, register_node_type

logger = logging.getLogger(__name__)

CATALOG_DIR = Path(BASE_DIR) / "catalogs"

# `component_type` is a String(30) column and the SQLAlchemy polymorphic
# discriminator, so a derived name that overflows is not a cosmetic problem: it
# would be silently truncated by some backends and collide with its neighbour.
# Refuse instead.
MAX_COMPONENT_TYPE = 30

# The contract restricts an output's type to exactly the JSON types, which is why
# this mapping is total and needs no fallback for "some type we have not seen".
# `null` alone carries no information about the value's shape, so it maps to ANY.
_TYPE_MAP = {
    "string": DataType.STRING,
    "number": DataType.NUMBER,
    "boolean": DataType.BOOLEAN,
    "object": DataType.OBJECT,
    "array": DataType.ARRAY,
    "null": DataType.ANY,
}


def component_type_for(binary: str, domain: str) -> str:
    """Derive a node type name from a binary and one of its domains.

    Deliberately mechanical: no per-binary special cases, no stripping of
    organisation prefixes. A rule that knows about one binary's naming is a rule
    the next binary breaks, and the prefix is also what keeps two binaries that
    both have a `funding` domain from colliding.
    """
    return f"{binary}_{domain}".replace("-", "_")


def _read_catalog(path: Path) -> dict[str, Any] | None:
    """Read one catalog document, or return None with a reason logged.

    A malformed catalog disables its own node types and nothing else. It must not
    take down the server: the file is operator-supplied and may be half-written,
    from an incompatible binary, or absent entirely.
    """
    try:
        doc = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        logger.error("catalog %s is unreadable, skipping: %s", path.name, exc)
        return None

    # A catalog may be handed over either bare or still inside the envelope the
    # binary wrote to stdout. Accept both rather than making the refresh script
    # the only supported path in.
    if isinstance(doc.get("data"), dict) and "operations" in doc.get("data", {}):
        doc = doc["data"]

    if doc.get("protocol") != 1:
        logger.error(
            "catalog %s declares protocol %r, not 1 — refusing the WHOLE catalog "
            "rather than the operations we happen to recognise",
            path.name,
            doc.get("protocol"),
        )
        return None

    missing = [k for k in ("binary", "operations") if k not in doc]
    if missing:
        logger.error("catalog %s is missing %s, skipping", path.name, ", ".join(missing))
        return None
    return doc


def _ports_for(operations: list[dict[str, Any]]) -> list[PortDefinition]:
    """Union the declared outputs of every operation in one domain.

    One node type covers several operations, so its ports are the union rather
    than any single operation's set. A node therefore advertises ports that the
    currently selected operation may not emit; the component fills those with
    blanks, for the same reason `_blank_ports()` exists in the mailbox component.

    Where two operations declare the same port name with different types, the
    port widens to ANY rather than silently taking whichever was read first.
    """
    ports: dict[str, PortDefinition] = {}
    for op in operations:
        for out in op.get("outputs", []):
            name = out.get("name")
            if not name:
                continue
            data_type = _TYPE_MAP.get(out.get("type"), DataType.ANY)
            existing = ports.get(name)
            if existing is None:
                ports[name] = PortDefinition(
                    name=name,
                    data_type=data_type,
                    description=out.get("description", ""),
                )
            elif existing.data_type != data_type:
                ports[name] = existing.model_copy(
                    update={
                        "data_type": DataType.ANY,
                        "description": (
                            f"{existing.description} (type varies by operation)"
                        ),
                    }
                )
    return list(ports.values())


def _spec_for(binary: str, domain: str, operations: list[dict[str, Any]]) -> NodeTypeSpec:
    ops = sorted(operations, key=lambda o: o["id"])
    return NodeTypeSpec(
        component_type=component_type_for(binary, domain),
        display_name=f"{binary} · {domain}",
        description=(
            f"{len(ops)} operation{'s' if len(ops) != 1 else ''} from the "
            f"{binary} binary, {domain} domain. The operation is chosen in the "
            f"node's config; the ports are the union of what those operations emit."
        ),
        category="action",
        inputs=[
            PortDefinition(
                name="input",
                data_type=DataType.ANY,
                required=False,
                description="Optional upstream value; parameters come from config",
            )
        ],
        outputs=_ports_for(ops),
        config_schema={
            "type": "object",
            "properties": {
                "operation": {
                    "type": "string",
                    "title": "Operation",
                    "enum": [o["id"] for o in ops],
                },
                "session": {
                    "type": "string",
                    "title": "Session",
                    "description": "Identity handle held by the binary. Required by some operations.",
                },
                "env": {
                    "type": "string",
                    "title": "Environment",
                    "description": "Environment name registered with the binary.",
                },
            },
            "required": ["operation"],
            # Sidecar detail the config form needs and JSON Schema has nowhere to
            # put: the per-operation parameter schemas and what each one is for.
            "x-binary": binary,
            "x-operations": {
                o["id"]: {
                    "summary": o.get("summary", ""),
                    "params": o.get("params", {}),
                    "session_required": bool(o.get("session", {}).get("required")),
                    "timeout_default_s": o.get("timeout_default_s"),
                    "outputs": [out.get("name") for out in o.get("outputs", [])],
                }
                for o in ops
            },
        },
    )


def load_specs(catalog_dir: Path | None = None) -> list[NodeTypeSpec]:
    """Derive and register one node type per (binary, domain). Returns them."""
    directory = catalog_dir or CATALOG_DIR
    specs: list[NodeTypeSpec] = []
    if not directory.is_dir():
        return specs

    for path in sorted(directory.glob("*.json")):
        doc = _read_catalog(path)
        if doc is None:
            continue
        binary = doc["binary"]
        by_domain: dict[str, list[dict[str, Any]]] = {}
        for op in doc["operations"]:
            if "id" not in op or "domain" not in op:
                logger.error("catalog %s has an operation missing id or domain, skipping it", path.name)
                continue
            by_domain.setdefault(op["domain"], []).append(op)

        for domain, ops in sorted(by_domain.items()):
            name = component_type_for(binary, domain)
            if len(name) > MAX_COMPONENT_TYPE:
                logger.error(
                    "node type %r is %d characters and the column holds %d — skipping. "
                    "Truncating would collide with a neighbouring domain.",
                    name,
                    len(name),
                    MAX_COMPONENT_TYPE,
                )
                continue
            specs.append(register_node_type(_spec_for(binary, domain, ops)))

    if specs:
        logger.info(
            "registered %d node type(s) from %d catalog(s) in %s",
            len(specs),
            len({s.config_schema["x-binary"] for s in specs}),
            directory,
        )
    return specs


def register_config_classes(base: type, registry: dict[str, type]) -> None:
    """Give every derived node type a mapped config class.

    Called by `models.node` with its own base and lookup table, so this module
    never imports the models — the dependency runs one way and there is no import
    cycle. SQLAlchemy keys single-table inheritance on the polymorphic identity,
    and an identity with no class raises when a row of that type is loaded, so a
    class must exist for every type a node might carry.
    """
    for component_type in _derived_component_types():
        if component_type in registry:
            continue
        cls = type(
            f"_BinaryConfig_{component_type}",
            (base,),
            {"__mapper_args__": {"polymorphic_identity": component_type}},
        )
        registry[component_type] = cls


def _derived_component_types() -> list[str]:
    """Registered types that came from a catalog, identified by their sidecar."""
    from schemas.node_types import NODE_TYPE_REGISTRY

    return [
        ct for ct, spec in NODE_TYPE_REGISTRY.items() if "x-binary" in spec.config_schema
    ]
