"""add max_execution_seconds to workflows

Revision ID: 34c15bdd588b
Revises: 7987571a36ca
Create Date: 2026-03-01 15:31:19.471202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c15bdd588b'
down_revision: Union[str, Sequence[str], None] = '7987571a36ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('max_execution_seconds', sa.Integer(), server_default=sa.text('600'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'max_execution_seconds')
    # ### end Alembic commands ###
