"""add encrypted secret to tool_credentials

`tool_credentials.config` is a plain JSON column, so a ToolCredential has had
nowhere safe to keep a secret — anything sensitive was stored in the clear. This
adds an encrypted column alongside it, matching how `llm_credentials.api_key`
and the `git_credentials` secrets are already handled.

The first consumer is the mailbox credential, whose `x-admin-auth` value reads
and deletes every mailbox on the temp-mail instance.

Hand-written rather than autogenerated: `--autogenerate` also proposed dropping
the `epics` and `tasks` tables, dropping `user_profiles.telegram_user_id`, and
re-typing three existing encrypted columns — drift between the models and a dev
database, not intended schema change. Only the one column belongs here.

Revision ID: 3870bee8886b
Revises: c5d6e7f8a9b0
Create Date: 2026-08-16 15:18:04.359153

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from models.encrypted import EncryptedString

# revision identifiers, used by Alembic.
revision: str = '3870bee8886b'
down_revision: Union[str, Sequence[str], None] = 'c5d6e7f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the encrypted secret column.

    server_default="" backfills existing rows; EncryptedString passes falsy
    values through untouched on both bind and result, so an empty default reads
    back as an empty string rather than as a decryption failure.
    """
    op.add_column(
        "tool_credentials",
        sa.Column("secret", EncryptedString(length=500), nullable=False, server_default=""),
    )


def downgrade() -> None:
    op.drop_column("tool_credentials", "secret")
