"""drop_deleted_at_from_workflows

Revision ID: 7987571a36ca
Revises: c8e05ca7246b
Create Date: 2026-02-27 21:59:24.523971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7987571a36ca'
down_revision: Union[str, Sequence[str], None] = 'c8e05ca7246b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up any soft-deleted rows before dropping the column
    op.execute("DELETE FROM workflows WHERE deleted_at IS NOT NULL")

    with op.batch_alter_table('workflows') as batch_op:
        batch_op.drop_column('deleted_at')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
