"""add_env_vars_to_workspace

Revision ID: c8e05ca7246b
Revises: d2b1542ce787
Create Date: 2026-02-27 21:26:37.356552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e05ca7246b'
down_revision: Union[str, Sequence[str], None] = 'd2b1542ce787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('env_vars', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'env_vars')
    # ### end Alembic commands ###
