"""Initial migration

Revision ID: ee58ce0cf036
Revises: 
Create Date: 2026-02-01 14:21:52.730275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee58ce0cf036'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tool_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('default_config', sa.JSON(), nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('github_username', sa.String(length=255), nullable=False),
    sa.Column('gitlab_username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=30), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('llm_credential_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('response_format', sa.JSON(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('code_language', sa.String(length=20), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name='fk_trigger_credential', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('git_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_credentials_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.Column('ssh_private_key', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('webhook_secret', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['base_credentials_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_credentials_id')
    )
    op.create_table('llm_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_credentials_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('custom_headers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['base_credentials_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_credentials_id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_llm_credential_id', sa.Integer(), nullable=True),
    sa.Column('default_llm_model_name', sa.String(length=255), nullable=False),
    sa.Column('default_timezone', sa.String(length=50), nullable=False),
    sa.Column('max_workflow_execution_seconds', sa.Integer(), nullable=False),
    sa.Column('confirmation_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('sandbox_code_execution', sa.Boolean(), nullable=False),
    sa.Column('feature_flags', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_llm_credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_credentials_id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.Text(), nullable=False),
    sa.Column('allowed_user_ids', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['base_credentials_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_credentials_id')
    )
    op.create_table('tool_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_credentials_id', sa.Integer(), nullable=False),
    sa.Column('tool_type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['base_credentials_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_credentials_id')
    )
    op.create_table('git_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('remote_url', sa.String(length=500), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=False),
    sa.Column('last_commit_hash', sa.String(length=40), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['git_credentials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_credential_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_definition_id', sa.Integer(), nullable=False),
    sa.Column('tool_credential_id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tool_credential_id'], ['tool_credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_definition_id'], ['tool_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('git_commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('files_changed', sa.JSON(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['git_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_hash')
    )
    op.create_table('git_sync_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('files_changed', sa.JSON(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['git_repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_callable', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('forked_from_id', sa.Integer(), nullable=True),
    sa.Column('error_handler_workflow_id', sa.Integer(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['error_handler_workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['forked_from_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['git_repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_slug'), 'workflows', ['slug'], unique=True)
    op.create_table('code_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('published_version_id', sa.Integer(), nullable=True),
    sa.Column('draft_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['draft_version_id'], ['code_block_versions.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['published_version_id'], ['code_block_versions.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('workflow_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.String(length=255), nullable=False),
    sa.Column('target_node_id', sa.String(length=255), nullable=False),
    sa.Column('edge_type', sa.String(length=15), nullable=False),
    sa.Column('edge_label', sa.String(length=20), nullable=False),
    sa.Column('condition_mapping', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('tool_definition_id', sa.Integer(), nullable=False),
    sa.Column('config_overrides', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_definition_id'], ['tool_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_block_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_block_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('expected_output', sa.JSON(), nullable=True),
    sa.Column('expected_error', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['code_block_id'], ['code_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_block_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_block_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('git_commit_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['code_block_id'], ['code_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['git_commit_id'], ['git_commits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_block_id', 'version_number', name='uq_codeblock_version')
    )
    op.create_table('workflow_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('component_type', sa.String(length=30), nullable=False),
    sa.Column('component_config_id', sa.Integer(), nullable=False),
    sa.Column('subworkflow_id', sa.Integer(), nullable=True),
    sa.Column('code_block_id', sa.Integer(), nullable=True),
    sa.Column('is_entry_point', sa.Boolean(), nullable=False),
    sa.Column('interrupt_before', sa.Boolean(), nullable=False),
    sa.Column('interrupt_after', sa.Boolean(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['code_block_id'], ['code_blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['component_config_id'], ['component_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subworkflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'node_id', name='uq_workflow_node_id')
    )
    op.create_table('code_block_test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['code_block_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['code_block_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_executions',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('trigger_node_id', sa.Integer(), nullable=True),
    sa.Column('parent_execution_id', sa.String(length=36), nullable=True),
    sa.Column('parent_node_id', sa.String(length=255), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('trigger_payload', sa.JSON(), nullable=True),
    sa.Column('final_output', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_execution_id'], ['workflow_executions.execution_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_node_id'], ['workflow_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.execution_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.execution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_tasks',
    sa.Column('task_id', sa.String(length=8), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.execution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations_conversation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('thread_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('metadata', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=True),
    sa.Column('user_profile_id', sa.BIGINT(), nullable=False),
    sa.Column('workflow_id', sa.BIGINT(), nullable=False),
    sa.CheckConstraint('(JSON_VALID("metadata") OR "metadata" IS NULL)'),
    sa.ForeignKeyConstraint(['execution_id'], ['workflows_workflowexecution.execution_id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_userprofile.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('conversations_conversation_workflow_id_60d8ff08'), 'conversations_conversation', ['workflow_id'], unique=False)
    op.create_index(op.f('conversations_conversation_user_profile_id_dfa0bca2'), 'conversations_conversation', ['user_profile_id'], unique=False)
    op.create_index(op.f('conversations_conversation_execution_id_60057cf4'), 'conversations_conversation', ['execution_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), 'django_content_type', ['app_label', 'model'], unique=1)
    op.create_table('workflows_gitrepository',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=20), nullable=False),
    sa.Column('remote_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('default_branch', sa.VARCHAR(length=100), nullable=False),
    sa.Column('local_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('last_commit_hash', sa.VARCHAR(length=40), nullable=False),
    sa.Column('last_synced_at', sa.DATETIME(), nullable=True),
    sa.Column('auto_sync_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('webhook_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('credential_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials_gitcredential.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_gitrepository_credential_id_8f1bf06b'), 'workflows_gitrepository', ['credential_id'], unique=False)
    op.create_table('workflows_gitsynctask',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('commit_message', sa.TEXT(), nullable=False),
    sa.Column('commit_hash', sa.VARCHAR(length=40), nullable=False),
    sa.Column('files_changed', sa.TEXT(), nullable=False),
    sa.Column('error_log', sa.TEXT(), nullable=False),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('max_retries', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('repository_id', sa.BIGINT(), nullable=False),
    sa.Column('triggered_by_id', sa.BIGINT(), nullable=True),
    sa.CheckConstraint('(JSON_VALID("files_changed") OR "files_changed" IS NULL)'),
    sa.ForeignKeyConstraint(['repository_id'], ['workflows_gitrepository.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users_userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_gitsynctask_triggered_by_id_2cf422ac'), 'workflows_gitsynctask', ['triggered_by_id'], unique=False)
    op.create_index(op.f('workflows_gitsynctask_repository_id_77112908'), 'workflows_gitsynctask', ['repository_id'], unique=False)
    op.create_table('workflows_workflowedge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_node_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('target_node_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('edge_type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('condition_mapping', sa.TEXT(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('workflow_id', sa.BIGINT(), nullable=False),
    sa.Column('edge_label', sa.VARCHAR(length=20), nullable=False),
    sa.CheckConstraint('(JSON_VALID("condition_mapping") OR "condition_mapping" IS NULL)'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_workflowedge_workflow_id_a3c150a4'), 'workflows_workflowedge', ['workflow_id'], unique=False)
    op.create_table('workflows_codeblocktest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('input_data', sa.TEXT(), nullable=False),
    sa.Column('expected_output', sa.TEXT(), nullable=True),
    sa.Column('expected_error', sa.VARCHAR(length=500), nullable=False),
    sa.Column('code_block_id', sa.BIGINT(), nullable=False),
    sa.CheckConstraint('(JSON_VALID("expected_output") OR "expected_output" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("input_data") OR "input_data" IS NULL)'),
    sa.ForeignKeyConstraint(['code_block_id'], ['workflows_codeblock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_codeblocktest_code_block_id_f15cd036'), 'workflows_codeblocktest', ['code_block_id'], unique=False)
    op.create_table('credentials_toolcredential',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tool_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('config', sa.TEXT(), nullable=False),
    sa.Column('base_credentials_id', sa.BIGINT(), nullable=False),
    sa.CheckConstraint('(JSON_VALID("config") OR "config" IS NULL)'),
    sa.ForeignKeyConstraint(['base_credentials_id'], ['credentials_basecredentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_toolcredentialmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('tool_credential_id', sa.BIGINT(), nullable=False),
    sa.Column('user_profile_id', sa.BIGINT(), nullable=False),
    sa.Column('tool_definition_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['tool_credential_id'], ['credentials_toolcredential.id'], ),
    sa.ForeignKeyConstraint(['tool_definition_id'], ['workflows_tooldefinition.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_toolcredentialmapping_user_profile_id_2e89b27c'), 'workflows_toolcredentialmapping', ['user_profile_id'], unique=False)
    op.create_index(op.f('workflows_toolcredentialmapping_tool_definition_id_063ebbbe'), 'workflows_toolcredentialmapping', ['tool_definition_id'], unique=False)
    op.create_index(op.f('workflows_toolcredentialmapping_tool_credential_id_17072c06'), 'workflows_toolcredentialmapping', ['tool_credential_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), 'auth_permission', ['content_type_id', 'codename'], unique=1)
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('workflows_tooldefinition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tool_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('input_schema', sa.TEXT(), nullable=True),
    sa.Column('default_config', sa.TEXT(), nullable=False),
    sa.Column('credential_type', sa.VARCHAR(length=20), nullable=False),
    sa.CheckConstraint('(JSON_VALID("default_config") OR "default_config" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("input_schema") OR "input_schema" IS NULL)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials_gitcredential',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=20), nullable=False),
    sa.Column('credential_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ssh_private_key', sa.TEXT(), nullable=False),
    sa.Column('access_token', sa.TEXT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('webhook_secret', sa.VARCHAR(length=255), nullable=False),
    sa.Column('base_credentials_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['base_credentials_id'], ['credentials_basecredentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_pendingtask',
    sa.Column('task_id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('telegram_chat_id', sa.BIGINT(), nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('user_profile_id', sa.BIGINT(), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflows_workflowexecution.execution_id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_userprofile.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('workflows_pendingtask_user_profile_id_7113cc26'), 'workflows_pendingtask', ['user_profile_id'], unique=False)
    op.create_index(op.f('workflows_pendingtask_execution_id_160ab733'), 'workflows_pendingtask', ['execution_id'], unique=False)
    op.create_table('users_userprofile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_user_id', sa.BIGINT(), nullable=True),
    sa.Column('github_username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('gitlab_username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_othercomponentconfig',
    sa.Column('basecomponentconfig_ptr_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['basecomponentconfig_ptr_id'], ['workflows_basecomponentconfig.id'], ),
    sa.PrimaryKeyConstraint('basecomponentconfig_ptr_id')
    )
    op.create_table('workflows_toolcomponentconfig',
    sa.Column('basecomponentconfig_ptr_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['basecomponentconfig_ptr_id'], ['workflows_basecomponentconfig.id'], ),
    sa.PrimaryKeyConstraint('basecomponentconfig_ptr_id')
    )
    op.create_table('credentials_llmprovidercredentials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('api_key', sa.TEXT(), nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('base_credentials_id', sa.BIGINT(), nullable=False),
    sa.Column('custom_headers', sa.TEXT(), nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('provider_type', sa.VARCHAR(length=30), nullable=False),
    sa.CheckConstraint('(JSON_VALID("custom_headers") OR "custom_headers" IS NULL)'),
    sa.ForeignKeyConstraint(['base_credentials_id'], ['credentials_basecredentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', sa.INTEGER(), nullable=False),
    sa.Column('change_message', sa.TEXT(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action_time', sa.DATETIME(), nullable=False),
    sa.CheckConstraint('"action_flag" >= 0'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('django_admin_log_user_id_c564eba6'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('django_admin_log_content_type_id_c4bce8eb'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('workflows_gitcommit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('commit_hash', sa.VARCHAR(length=40), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('files_changed', sa.TEXT(), nullable=False),
    sa.Column('additions', sa.INTEGER(), nullable=False),
    sa.Column('deletions', sa.INTEGER(), nullable=False),
    sa.Column('committed_at', sa.DATETIME(), nullable=False),
    sa.Column('synced_at', sa.DATETIME(), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=True),
    sa.Column('repository_id', sa.BIGINT(), nullable=False),
    sa.CheckConstraint('(JSON_VALID("files_changed") OR "files_changed" IS NULL)'),
    sa.ForeignKeyConstraint(['author_id'], ['users_userprofile.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['workflows_gitrepository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_gitcommit_repository_id_df8ad31d'), 'workflows_gitcommit', ['repository_id'], unique=False)
    op.create_index(op.f('workflows_gitcommit_author_id_5db3169c'), 'workflows_gitcommit', ['author_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('applied', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_systemconfig',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('default_timezone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('max_workflow_execution_seconds', sa.INTEGER(), nullable=False),
    sa.Column('confirmation_timeout_seconds', sa.INTEGER(), nullable=False),
    sa.Column('sandbox_code_execution', sa.BOOLEAN(), nullable=False),
    sa.Column('feature_flags', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('default_llm_credential_id', sa.BIGINT(), nullable=True),
    sa.Column('default_llm_model_name', sa.VARCHAR(length=255), nullable=False),
    sa.CheckConstraint('(JSON_VALID("feature_flags") OR "feature_flags" IS NULL)'),
    sa.ForeignKeyConstraint(['default_llm_credential_id'], ['credentials_basecredentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('system_systemconfig_default_llm_credential_id_25b56b5e'), 'system_systemconfig', ['default_llm_credential_id'], unique=False)
    op.create_table('workflows_triggercomponentconfig',
    sa.Column('basecomponentconfig_ptr_id', sa.BIGINT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('trigger_config', sa.TEXT(), nullable=False),
    sa.Column('credential_id', sa.BIGINT(), nullable=True),
    sa.CheckConstraint('(JSON_VALID("trigger_config") OR "trigger_config" IS NULL)'),
    sa.ForeignKeyConstraint(['basecomponentconfig_ptr_id'], ['workflows_basecomponentconfig.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials_basecredentials.id'], ),
    sa.PrimaryKeyConstraint('basecomponentconfig_ptr_id')
    )
    op.create_index(op.f('workflows_triggercomponentconfig_credential_id_d9238c5a'), 'workflows_triggercomponentconfig', ['credential_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), 'auth_user_groups', ['user_id', 'group_id'], unique=1)
    op.create_index(op.f('auth_user_groups_user_id_6a12ed8b'), 'auth_user_groups', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_groups_group_id_97559544'), 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', sa.TEXT(), nullable=False),
    sa.Column('expire_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('workflows_workflowcollaborator',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('invited_at', sa.DATETIME(), nullable=False),
    sa.Column('accepted_at', sa.DATETIME(), nullable=True),
    sa.Column('invited_by_id', sa.BIGINT(), nullable=True),
    sa.Column('user_profile_id', sa.BIGINT(), nullable=False),
    sa.Column('workflow_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users_userprofile.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_userprofile.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_workflowcollaborator_workflow_id_user_profile_id_ab2f96a3_uniq'), 'workflows_workflowcollaborator', ['workflow_id', 'user_profile_id'], unique=1)
    op.create_index(op.f('workflows_workflowcollaborator_workflow_id_a7fae0f7'), 'workflows_workflowcollaborator', ['workflow_id'], unique=False)
    op.create_index(op.f('workflows_workflowcollaborator_user_profile_id_48762982'), 'workflows_workflowcollaborator', ['user_profile_id'], unique=False)
    op.create_index(op.f('workflows_workflowcollaborator_invited_by_id_b9f43923'), 'workflows_workflowcollaborator', ['invited_by_id'], unique=False)
    op.create_table('users_apikey',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_executionlog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('input', sa.TEXT(), nullable=True),
    sa.Column('output', sa.TEXT(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=False),
    sa.CheckConstraint('(JSON_VALID("input") OR "input" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("output") OR "output" IS NULL)'),
    sa.ForeignKeyConstraint(['execution_id'], ['workflows_workflowexecution.execution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_executionlog_execution_id_3a5dcb00'), 'workflows_executionlog', ['execution_id'], unique=False)
    op.create_table('workflows_codeblock',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('language', sa.VARCHAR(length=20), nullable=False),
    sa.Column('timeout_seconds', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('draft_version_id', sa.BIGINT(), nullable=True),
    sa.Column('published_version_id', sa.BIGINT(), nullable=True),
    sa.Column('workflow_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['draft_version_id'], ['workflows_codeblockversion.id'], ),
    sa.ForeignKeyConstraint(['published_version_id'], ['workflows_codeblockversion.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_codeblock_workflow_id_21998300'), 'workflows_codeblock', ['workflow_id'], unique=False)
    op.create_index(op.f('workflows_codeblock_published_version_id_7fb6d4ad'), 'workflows_codeblock', ['published_version_id'], unique=False)
    op.create_index(op.f('workflows_codeblock_draft_version_id_f8222242'), 'workflows_codeblock', ['draft_version_id'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), 'auth_user_user_permissions', ['user_id', 'permission_id'], unique=1)
    op.create_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), 'auth_group_permissions', ['group_id', 'permission_id'], unique=1)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('workflows_workflownode',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('is_entry_point', sa.BOOLEAN(), nullable=False),
    sa.Column('interrupt_before', sa.BOOLEAN(), nullable=False),
    sa.Column('interrupt_after', sa.BOOLEAN(), nullable=False),
    sa.Column('position_x', sa.INTEGER(), nullable=False),
    sa.Column('position_y', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('code_block_id', sa.BIGINT(), nullable=True),
    sa.Column('subworkflow_id', sa.BIGINT(), nullable=True),
    sa.Column('workflow_id', sa.BIGINT(), nullable=False),
    sa.Column('component_config_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['code_block_id'], ['workflows_codeblock.id'], ),
    sa.ForeignKeyConstraint(['component_config_id'], ['workflows_basecomponentconfig.id'], ),
    sa.ForeignKeyConstraint(['subworkflow_id'], ['workflows_workflow.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_workflownode_workflow_id_node_id_25d1dba5_uniq'), 'workflows_workflownode', ['workflow_id', 'node_id'], unique=1)
    op.create_index(op.f('workflows_workflownode_workflow_id_2de99647'), 'workflows_workflownode', ['workflow_id'], unique=False)
    op.create_index(op.f('workflows_workflownode_subworkflow_id_766a4be0'), 'workflows_workflownode', ['subworkflow_id'], unique=False)
    op.create_index(op.f('workflows_workflownode_component_config_id_0916047e'), 'workflows_workflownode', ['component_config_id'], unique=False)
    op.create_index(op.f('workflows_workflownode_code_block_id_d477ce1b'), 'workflows_workflownode', ['code_block_id'], unique=False)
    op.create_table('credentials_telegramcredential',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bot_token', sa.TEXT(), nullable=False),
    sa.Column('allowed_user_ids', sa.VARCHAR(length=500), nullable=False),
    sa.Column('base_credentials_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['base_credentials_id'], ['credentials_basecredentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_modelcomponentconfig',
    sa.Column('basecomponentconfig_ptr_id', sa.BIGINT(), nullable=False),
    sa.Column('frequency_penalty', sa.REAL(), nullable=True),
    sa.Column('max_retries', sa.INTEGER(), nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('presence_penalty', sa.REAL(), nullable=True),
    sa.Column('response_format', sa.TEXT(), nullable=True),
    sa.Column('temperature', sa.REAL(), nullable=True),
    sa.Column('timeout', sa.INTEGER(), nullable=True),
    sa.Column('top_p', sa.REAL(), nullable=True),
    sa.Column('llm_credential_id', sa.BIGINT(), nullable=True),
    sa.CheckConstraint('(JSON_VALID("response_format") OR "response_format" IS NULL)'),
    sa.ForeignKeyConstraint(['basecomponentconfig_ptr_id'], ['workflows_basecomponentconfig.id'], ),
    sa.ForeignKeyConstraint(['llm_credential_id'], ['credentials_basecredentials.id'], ),
    sa.PrimaryKeyConstraint('basecomponentconfig_ptr_id')
    )
    op.create_index(op.f('workflows_modelcomponentconfig_llm_credential_id_7dcaa83e'), 'workflows_modelcomponentconfig', ['llm_credential_id'], unique=False)
    op.create_table('workflows_codeblocktestrun',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('passed', sa.BOOLEAN(), nullable=False),
    sa.Column('actual_output', sa.TEXT(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=False),
    sa.Column('execution_time_ms', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('test_id', sa.BIGINT(), nullable=False),
    sa.Column('version_id', sa.BIGINT(), nullable=False),
    sa.CheckConstraint('(JSON_VALID("actual_output") OR "actual_output" IS NULL)'),
    sa.ForeignKeyConstraint(['test_id'], ['workflows_codeblocktest.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['workflows_codeblockversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_codeblocktestrun_version_id_bacc6146'), 'workflows_codeblocktestrun', ['version_id'], unique=False)
    op.create_index(op.f('workflows_codeblocktestrun_test_id_1ff85d26'), 'workflows_codeblocktestrun', ['test_id'], unique=False)
    op.create_table('workflows_workflowtool',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('config_overrides', sa.TEXT(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('tool_definition_id', sa.BIGINT(), nullable=False),
    sa.Column('workflow_id', sa.BIGINT(), nullable=False),
    sa.CheckConstraint('(JSON_VALID("config_overrides") OR "config_overrides" IS NULL)'),
    sa.ForeignKeyConstraint(['tool_definition_id'], ['workflows_tooldefinition.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_workflowtool_workflow_id_87055ca8'), 'workflows_workflowtool', ['workflow_id'], unique=False)
    op.create_index(op.f('workflows_workflowtool_tool_definition_id_7f5072bd'), 'workflows_workflowtool', ['tool_definition_id'], unique=False)
    op.create_table('workflows_codeblockversion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('input_schema', sa.TEXT(), nullable=True),
    sa.Column('output_schema', sa.TEXT(), nullable=True),
    sa.Column('requirements', sa.TEXT(), nullable=False),
    sa.Column('commit_message', sa.TEXT(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=True),
    sa.Column('code_block_id', sa.BIGINT(), nullable=False),
    sa.Column('git_commit_id', sa.BIGINT(), nullable=True),
    sa.CheckConstraint('(JSON_VALID("input_schema") OR "input_schema" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("output_schema") OR "output_schema" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("requirements") OR "requirements" IS NULL)'),
    sa.ForeignKeyConstraint(['author_id'], ['users_userprofile.id'], ),
    sa.ForeignKeyConstraint(['code_block_id'], ['workflows_codeblock.id'], ),
    sa.ForeignKeyConstraint(['git_commit_id'], ['workflows_gitcommit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_codeblockversion_git_commit_id_247d9ee0'), 'workflows_codeblockversion', ['git_commit_id'], unique=False)
    op.create_index(op.f('workflows_codeblockversion_code_block_id_version_number_8cb60125_uniq'), 'workflows_codeblockversion', ['code_block_id', 'version_number'], unique=1)
    op.create_index(op.f('workflows_codeblockversion_code_block_id_1401aa50'), 'workflows_codeblockversion', ['code_block_id'], unique=False)
    op.create_index(op.f('workflows_codeblockversion_author_id_8e7afad7'), 'workflows_codeblockversion', ['author_id'], unique=False)
    op.create_table('workflows_aicomponentconfig',
    sa.Column('basecomponentconfig_ptr_id', sa.BIGINT(), nullable=False),
    sa.Column('system_prompt', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['basecomponentconfig_ptr_id'], ['workflows_basecomponentconfig.id'], ),
    sa.PrimaryKeyConstraint('basecomponentconfig_ptr_id')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('date_joined', sa.DATETIME(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_basecomponentconfig',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('extra_config', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint('(JSON_VALID("extra_config") OR "extra_config" IS NULL)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_workflowexecution',
    sa.Column('execution_id', sa.CHAR(length=32), nullable=False),
    sa.Column('parent_node_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('thread_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('trigger_payload', sa.TEXT(), nullable=True),
    sa.Column('final_output', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('max_retries', sa.INTEGER(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('user_profile_id', sa.BIGINT(), nullable=False),
    sa.Column('workflow_id', sa.BIGINT(), nullable=False),
    sa.Column('parent_execution_id', sa.CHAR(length=32), nullable=True),
    sa.Column('trigger_node_id', sa.BIGINT(), nullable=True),
    sa.CheckConstraint('(JSON_VALID("final_output") OR "final_output" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("trigger_payload") OR "trigger_payload" IS NULL)'),
    sa.ForeignKeyConstraint(['parent_execution_id'], ['workflows_workflowexecution.execution_id'], ),
    sa.ForeignKeyConstraint(['trigger_node_id'], ['workflows_workflownode.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_userprofile.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows_workflow.id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('workflows_workflowexecution_workflow_id_b382211d'), 'workflows_workflowexecution', ['workflow_id'], unique=False)
    op.create_index(op.f('workflows_workflowexecution_user_profile_id_97f41cf7'), 'workflows_workflowexecution', ['user_profile_id'], unique=False)
    op.create_index(op.f('workflows_workflowexecution_trigger_node_id_2de2ad9e'), 'workflows_workflowexecution', ['trigger_node_id'], unique=False)
    op.create_index(op.f('workflows_workflowexecution_parent_execution_id_475a99d0'), 'workflows_workflowexecution', ['parent_execution_id'], unique=False)
    op.create_table('workflows_codecomponentconfig',
    sa.Column('basecomponentconfig_ptr_id', sa.BIGINT(), nullable=False),
    sa.Column('code_language', sa.VARCHAR(length=20), nullable=False),
    sa.Column('code_snippet', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['basecomponentconfig_ptr_id'], ['workflows_basecomponentconfig.id'], ),
    sa.PrimaryKeyConstraint('basecomponentconfig_ptr_id')
    )
    op.create_table('workflows_workflow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('is_template', sa.BOOLEAN(), nullable=False),
    sa.Column('is_callable', sa.BOOLEAN(), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('input_schema', sa.TEXT(), nullable=True),
    sa.Column('output_schema', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('owner_id', sa.BIGINT(), nullable=False),
    sa.Column('repository_id', sa.BIGINT(), nullable=True),
    sa.Column('error_handler_workflow_id', sa.BIGINT(), nullable=True),
    sa.Column('forked_from_id', sa.BIGINT(), nullable=True),
    sa.CheckConstraint('(JSON_VALID("input_schema") OR "input_schema" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("output_schema") OR "output_schema" IS NULL)'),
    sa.ForeignKeyConstraint(['error_handler_workflow_id'], ['workflows_workflow.id'], ),
    sa.ForeignKeyConstraint(['forked_from_id'], ['workflows_workflow.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users_userprofile.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['workflows_gitrepository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('workflows_workflow_owner_id_7e397794'), 'workflows_workflow', ['owner_id'], unique=False)
    op.create_index(op.f('workflows_workflow_forked_from_id_08689a35'), 'workflows_workflow', ['forked_from_id'], unique=False)
    op.create_index(op.f('workflows_workflow_error_handler_workflow_id_4db00d0c'), 'workflows_workflow', ['error_handler_workflow_id'], unique=False)
    op.create_table('credentials_basecredentials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('credential_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('user_profile_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('credentials_basecredentials_user_profile_id_9dc1668a'), 'credentials_basecredentials', ['user_profile_id'], unique=False)
    op.drop_table('pending_tasks')
    op.drop_table('execution_logs')
    op.drop_table('conversations')
    op.drop_table('workflow_executions')
    op.drop_table('code_block_test_runs')
    op.drop_table('workflow_nodes')
    op.drop_table('code_block_versions')
    op.drop_table('code_block_tests')
    op.drop_table('workflow_tools')
    op.drop_table('workflow_edges')
    op.drop_table('workflow_collaborators')
    op.drop_table('code_blocks')
    op.drop_index(op.f('ix_workflows_slug'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_table('git_sync_tasks')
    op.drop_table('git_commits')
    op.drop_table('tool_credential_mappings')
    op.drop_table('git_repositories')
    op.drop_table('tool_credentials')
    op.drop_table('telegram_credentials')
    op.drop_table('system_config')
    op.drop_table('llm_credentials')
    op.drop_table('git_credentials')
    op.drop_table('component_configs')
    op.drop_table('credentials')
    op.drop_table('api_keys')
    op.drop_table('user_profiles')
    op.drop_table('tool_definitions')
    # ### end Alembic commands ###
