server: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
frontend: npm --prefix frontend run dev
worker1: rq worker --worker-class worker_class.PipelitWorker workflows --with-scheduler
worker2: rq worker --worker-class worker_class.PipelitWorker workflows
