# Generated by Django 6.0.1 on 2026-01-30 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_timezone', models.CharField(default='UTC', max_length=50)),
                ('max_workflow_execution_seconds', models.IntegerField(default=600)),
                ('confirmation_timeout_seconds', models.IntegerField(default=300)),
                ('sandbox_code_execution', models.BooleanField(default=False)),
                ('feature_flags', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.llmmodel')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
