# Generated by Django 6.0.1 on 2026-01-31 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_simplify_llm_credentials'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='default_llm_model',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='default_llm_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.basecredentials'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='default_llm_model_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
