# Generated by Django 6.0.1 on 2026-01-30 02:39

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openai_compatible', 'OpenAI Compatible')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credential_type', models.CharField(choices=[('git', 'Git'), ('llm', 'LLM Provider'), ('telegram', 'Telegram'), ('tool', 'Tool')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='users.userprofile')),
            ],
            options={
                'verbose_name_plural': 'base credentials',
            },
        ),
        migrations.CreateModel(
            name='GitCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=20)),
                ('credential_type', models.CharField(choices=[('ssh_key', 'SSH Key'), ('token', 'Token'), ('app', 'App')], max_length=20)),
                ('ssh_private_key', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('base_credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='git_credential', to='credentials.basecredentials')),
            ],
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('default_temperature', models.FloatField(default=0.7)),
                ('context_window', models.IntegerField(default=4096)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='credentials.llmprovider')),
            ],
        ),
        migrations.CreateModel(
            name='LLMProviderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('base_url', models.URLField(blank=True, default='')),
                ('base_credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_credential', to='credentials.basecredentials')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='credentials.llmprovider')),
            ],
            options={
                'verbose_name_plural': 'LLM provider credentials',
            },
        ),
        migrations.CreateModel(
            name='TelegramCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', encrypted_model_fields.fields.EncryptedCharField()),
                ('allowed_user_ids', models.CharField(blank=True, default='', help_text='Comma-separated Telegram user IDs', max_length=500)),
                ('base_credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_credential', to='credentials.basecredentials')),
            ],
        ),
        migrations.CreateModel(
            name='ToolCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('searxng', 'SearXNG'), ('browser', 'Browser'), ('api', 'API')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Tool-specific config (sensitive fields encrypted at app layer)')),
                ('base_credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_credential', to='credentials.basecredentials')),
            ],
        ),
    ]
