# Generated by Django 6.0.1 on 2026-01-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmmodel',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='llmprovidercredentials',
            name='provider',
        ),
        migrations.AddField(
            model_name='llmprovidercredentials',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmprovidercredentials',
            name='organization_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='llmprovidercredentials',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openai_compatible', 'OpenAI Compatible')], default='openai_compatible', max_length=30),
        ),
    ]
