# Generated by Django 6.0.1 on 2026-01-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_simplify_llm_credentials'),
        ('system', '0002_simplify_llm_credentials'),
        ('workflows', '0005_simplify_llm_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LLMModel',
        ),
        migrations.DeleteModel(
            name='LLMProvider',
        ),
    ]
